---
all:

  hosts:

    # tx node
    1.2.3.4:
      besu_bootnodes: ["enode://7c6e935eca89b230002294420c10d645844419ac50c5fc03fa53bf24fd82600508f5a4d5b89f7690c7e8f9c5dc833605d60bb1dd35997669ab7f1fc274683803@54.162.14.76:30303","enode://2f5d0489e2bbbc495e3d38ae3df9cc0a47faf42818057d193f0f4863d44505277c3d1b9a863f7ad961830ef15a8f8b72ec52791f3cca5ef84284a29f82f2dd73@18.235.20.166:30303"]
      besu_host_ip: 1.2.3.4

    # validator node
    # 1.2.3.4:
    #   besu_bootnodes: ["enode://7c6e935eca89b230002294420c10d645844419ac50c5fc03fa53bf24fd82600508f5a4d5b89f7690c7e8f9c5dc833605d60bb1dd35997669ab7f1fc274683803@54.162.14.76:30303","enode://2f5d0489e2bbbc495e3d38ae3df9cc0a47faf42818057d193f0f4863d44505277c3d1b9a863f7ad961830ef15a8f8b72ec52791f3cca5ef84284a29f82f2dd73@18.235.20.166:30303"]
    #   besu_host_ip: 1.2.3.4
    #   besu_permissions_nodes_config_file: /etc/besu/permissions_config.toml
    #   besu_node_private_key_file: /etc/besu/keys/key

  vars:
    besu_version: "22.4.0"
    besu_env_opts: [ "-Dlog4j2.formatMsgNoLookups=True" ]
    besu_data_dir: "/data"
    besu_sync_mode: "FULL"
    besu_genesis_path: /etc/besu/genesis.json
    besu_rpc_http_api: ["DEBUG","NET","WEB3","ETH","ADMIN","IBFT","TRACE"]
    besu_network: "palm"
    remote_user: "ec2-user"


